import purity from "../../../public/images/purity.png";
import father from "../../../public/images/father.png";
import psychologist from "../../../public/images/psychologist.png";
import pastor from "../../../public/images/pastor.png";

export const AboutContents = [
  {
    image: purity,
    title: "Purity, Power & Prosperity",
    info: "<p>Lorem ipsum doTelor sit amet consectetur. In risus diam orci arcupell entesque feugiat dui sed lacus. Quis aliquet nisi suspendisseat gravida enim sed. Integer sit vitae aliquam dictumst facilisissed. Porta aliquam morbi et dolor. Convallis quis vestibulum consequat turpis vivamus sem. Sed ut quis placerat fames. Nibhmauris ultrices ut euismod sit placerat lacinia sem quam. Posuere turpis convallis tellus quis in suspendisse. Felis faucibus tellus quam ultrices gravida massa duis sit venenatis. Tellus pulvinar facilisis enim in risus nisi morbi egestas in. Enim porttitor malesuada massa massa non nec non diam. Amet congue velit ultrices dolor in. Neque duis platea eleifend dolor ullamcorper egestasornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p><p>In magna nulla faucibus justo nulla eu suspendisse. Tortor porta cursus eget egestas vitae id. Diam platea lectus a pellentesque ut egestas proin tellus mi. Pellentesque purus dignissim amet turpis rutrum. Nibh scelerisque blandit mattis egestas nisi commodo sit at. Volutpat et scelerisque felis nec integer. Phasellus quis risus lorem sagittis purus quisque tempor pellentesque sed nunc. Dignissim adipiscing adipiscing etiam integer euismod congue ac. Pulvinar morbi dui fames commodo faucibus id ante eget sit. Dolor gravida turpis arcu magna vel lacus a. Arcu ullamcorper gravida egestas nunc risus proin nisl id. Magna pharetra dolor pulvinar lorem. Tempus aliquam malesuada senectus amet sed lectus. Malesuada facilisis sem viverra auctor ut arcu faucibus elementum. Arcu morbi sit et vulputate arcu. Pellentesque et consectetur consectetur lacus phasellus enim pellentesque porttitor. Est duis non nulla id. Donec in elit aliquam velit. Ipsum leo tincidunt in arcu nisl. Vitae scelerisque egestas id consequat massa a nulla consectetur. Eget orci blandit malesuada amet consectetur. Ac sit at gravida diam. Orci enim gravida vitae est arcu est turpis ornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p>",
  },
  {
    image: father,
    title: "Father",
    info: "<p>Lorem ipsum doTelor sit amet consectetur. In risus diam orci arcupell entesque feugiat dui sed lacus. Quis aliquet nisi suspendisseat gravida enim sed. Integer sit vitae aliquam dictumst facilisissed. Porta aliquam morbi et dolor. Convallis quis vestibulum consequat turpis vivamus sem. Sed ut quis placerat fames. Nibhmauris ultrices ut euismod sit placerat lacinia sem quam. Posuere turpis convallis tellus quis in suspendisse. Felis faucibus tellus quam ultrices gravida massa duis sit venenatis. Tellus pulvinar facilisis enim in risus nisi morbi egestas in. Enim porttitor malesuada massa massa non nec non diam. Amet congue velit ultrices dolor in. Neque duis platea eleifend dolor ullamcorper egestasornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p><p>In magna nulla faucibus justo nulla eu suspendisse. Tortor porta cursus eget egestas vitae id. Diam platea lectus a pellentesque ut egestas proin tellus mi. Pellentesque purus dignissim amet turpis rutrum. Nibh scelerisque blandit mattis egestas nisi commodo sit at. Volutpat et scelerisque felis nec integer. Phasellus quis risus lorem sagittis purus quisque tempor pellentesque sed nunc. Dignissim adipiscing adipiscing etiam integer euismod congue ac. Pulvinar morbi dui fames commodo faucibus id ante eget sit. Dolor gravida turpis arcu magna vel lacus a. Arcu ullamcorper gravida egestas nunc risus proin nisl id. Magna pharetra dolor pulvinar lorem. Tempus aliquam malesuada senectus amet sed lectus. Malesuada facilisis sem viverra auctor ut arcu faucibus elementum. Arcu morbi sit et vulputate arcu. Pellentesque et consectetur consectetur lacus phasellus enim pellentesque porttitor. Est duis non nulla id. Donec in elit aliquam velit. Ipsum leo tincidunt in arcu nisl. Vitae scelerisque egestas id consequat massa a nulla consectetur. Eget orci blandit malesuada amet consectetur. Ac sit at gravida diam. Orci enim gravida vitae est arcu est turpis ornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p>",
  },
  {
    image: psychologist,
    title: "Psychologist",
    info: "<p>Lorem ipsum doTelor sit amet consectetur. In risus diam orci arcupell entesque feugiat dui sed lacus. Quis aliquet nisi suspendisseat gravida enim sed. Integer sit vitae aliquam dictumst facilisissed. Porta aliquam morbi et dolor. Convallis quis vestibulum consequat turpis vivamus sem. Sed ut quis placerat fames. Nibhmauris ultrices ut euismod sit placerat lacinia sem quam. Posuere turpis convallis tellus quis in suspendisse. Felis faucibus tellus quam ultrices gravida massa duis sit venenatis. Tellus pulvinar facilisis enim in risus nisi morbi egestas in. Enim porttitor malesuada massa massa non nec non diam. Amet congue velit ultrices dolor in. Neque duis platea eleifend dolor ullamcorper egestasornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p><p>In magna nulla faucibus justo nulla eu suspendisse. Tortor porta cursus eget egestas vitae id. Diam platea lectus a pellentesque ut egestas proin tellus mi. Pellentesque purus dignissim amet turpis rutrum. Nibh scelerisque blandit mattis egestas nisi commodo sit at. Volutpat et scelerisque felis nec integer. Phasellus quis risus lorem sagittis purus quisque tempor pellentesque sed nunc. Dignissim adipiscing adipiscing etiam integer euismod congue ac. Pulvinar morbi dui fames commodo faucibus id ante eget sit. Dolor gravida turpis arcu magna vel lacus a. Arcu ullamcorper gravida egestas nunc risus proin nisl id. Magna pharetra dolor pulvinar lorem. Tempus aliquam malesuada senectus amet sed lectus. Malesuada facilisis sem viverra auctor ut arcu faucibus elementum. Arcu morbi sit et vulputate arcu. Pellentesque et consectetur consectetur lacus phasellus enim pellentesque porttitor. Est duis non nulla id. Donec in elit aliquam velit. Ipsum leo tincidunt in arcu nisl. Vitae scelerisque egestas id consequat massa a nulla consectetur. Eget orci blandit malesuada amet consectetur. Ac sit at gravida diam. Orci enim gravida vitae est arcu est turpis ornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p>",
    awards: [{ key: "Nigerian Psychological Association" }],
  },
  {
    image: pastor,
    title: "Pastor",
    info: "<p>Lorem ipsum doTelor sit amet consectetur. In risus diam orci arcupell entesque feugiat dui sed lacus. Quis aliquet nisi suspendisseat gravida enim sed. Integer sit vitae aliquam dictumst facilisissed. Porta aliquam morbi et dolor. Convallis quis vestibulum consequat turpis vivamus sem. Sed ut quis placerat fames. Nibhmauris ultrices ut euismod sit placerat lacinia sem quam. Posuere turpis convallis tellus quis in suspendisse. Felis faucibus tellus quam ultrices gravida massa duis sit venenatis. Tellus pulvinar facilisis enim in risus nisi morbi egestas in. Enim porttitor malesuada massa massa non nec non diam. Amet congue velit ultrices dolor in. Neque duis platea eleifend dolor ullamcorper egestasornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p><p>In magna nulla faucibus justo nulla eu suspendisse. Tortor porta cursus eget egestas vitae id. Diam platea lectus a pellentesque ut egestas proin tellus mi. Pellentesque purus dignissim amet turpis rutrum. Nibh scelerisque blandit mattis egestas nisi commodo sit at. Volutpat et scelerisque felis nec integer. Phasellus quis risus lorem sagittis purus quisque tempor pellentesque sed nunc. Dignissim adipiscing adipiscing etiam integer euismod congue ac. Pulvinar morbi dui fames commodo faucibus id ante eget sit. Dolor gravida turpis arcu magna vel lacus a. Arcu ullamcorper gravida egestas nunc risus proin nisl id. Magna pharetra dolor pulvinar lorem. Tempus aliquam malesuada senectus amet sed lectus. Malesuada facilisis sem viverra auctor ut arcu faucibus elementum. Arcu morbi sit et vulputate arcu. Pellentesque et consectetur consectetur lacus phasellus enim pellentesque porttitor. Est duis non nulla id. Donec in elit aliquam velit. Ipsum leo tincidunt in arcu nisl. Vitae scelerisque egestas id consequat massa a nulla consectetur. Eget orci blandit malesuada amet consectetur. Ac sit at gravida diam. Orci enim gravida vitae est arcu est turpis ornare. Vulputate dui suspendisse odio in penatibus pellentesque.</p>",
    awards: [{ key: "Charismatic Renewal Ministries" }],
  },
];
